AWSTemplateFormatVersion: 2010-09-09
Description: Reference Architecture to host WordPress on AWS - Create New Route53 Zone
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: DNS Configuration
        Parameters:
          - DomainName
    ParameterLabels:
      DomainName:
        default: Domain Name
Parameters:
  DomainName:
    Description: >-
      Domain Name configured for the cluster
    Type: String
    Default: ''
Resources:
  CreateZone:
    Type: 'AWS::Route53::HostedZone'
    Properties:
      Name: !Ref DomainName
Outputs:
  HostedZoneId:
    Value: !Ref CreateZone
