AWSTemplateFormatVersion: 2010-09-09

Description: Reference Architecture to host WordPress on AWS - Creates CloudFront distribution (if selected)

Metadata:
  Authors:
    Description: Darryl Osborne (darrylo@amazon.com)
  License:
    Description:
      'Copyright 2018 Amazon.com, Inc. and its affiliates. All Rights Reserved.
      Licensed under the Amazon Software License (the "License"). You may not use this file
      except in compliance with the License. A copy of the License is located at
      http://aws.amazon.com/asl/
      or in the "license" file accompanying this file. This file is distributed on an "AS IS"
      BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
      License for the specific language governing permissions and limitations under the License.'

  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: AWS Parameters
        Parameters:
          - WPDomainName
    ParameterLabels:
      WPDomainName:
        default: Domain name of the WordPress site

Parameters:
  WPDomainName:
    AllowedPattern: ^$|(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$
    Description: '[ Optional ] The main domain name of the WordPress site (e.g. example.com).'
    Type: String

Conditions:
  WPDomainName: !Not [!Equals ['', !Ref WPDomainName]]
Resources:
  CloudFront:
    Condition: WPDomainName
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        HttpVersion: http2
        Aliases:
          - !If [
              WPDomainName,
              !Join ['', ['*.', !Ref WPDomainName]],
              !Ref 'AWS::NoValue',
            ]
        CacheBehaviors:
          - PathPattern: wp-includes/*
            AllowedMethods:
              - DELETE
              - GET
              - HEAD
              - OPTIONS
              - PATCH
              - POST
              - PUT
            DefaultTTL: 900
            MaxTTL: 900
            MinTTL: 900
            ForwardedValues:
              QueryString: true
              Headers:
                - Host
            TargetOriginId: !Join ['', ['www.', !Ref WPDomainName]]
            ViewerProtocolPolicy: redirect-to-https
            Compress: true
          - PathPattern: wp-content/*
            AllowedMethods:
              - DELETE
              - GET
              - HEAD
              - OPTIONS
              - PATCH
              - POST
              - PUT
            DefaultTTL: 900
            MaxTTL: 900
            MinTTL: 900
            ForwardedValues:
              QueryString: true
              Headers:
                - Host
            TargetOriginId: !Join ['', ['www.', !Ref WPDomainName]]
            ViewerProtocolPolicy: redirect-to-https
            Compress: true
        Comment: !Ref 'AWS::StackName'
        DefaultCacheBehavior:
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          DefaultTTL: 0
          MaxTTL: 0
          MinTTL: 0
          ForwardedValues:
            QueryString: true
            Headers:
              - '*'
            Cookies:
              Forward: all
          TargetOriginId: !Join ['', ['www.', !Ref WPDomainName]]
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
        Enabled: true
        Origins:
          - DomainName: !Join ['', ['www.', !Ref WPDomainName]]
            Id: !Join ['', ['www.', !Ref WPDomainName]]
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
        PriceClass: PriceClass_100
