AWSTemplateFormatVersion: 2010-09-09

Description: Reference Architecture to host WordPress on AWS - Creates Route 53 record set

Metadata:
  Authors:
    Description: Darryl Osborne (darrylo@amazon.com)
  License:
    Description:
      'Copyright 2018 Amazon.com, Inc. and its affiliates. All Rights Reserved.
      Licensed under the Amazon Software License (the "License"). You may not use this file
      except in compliance with the License. A copy of the License is located at
      http://aws.amazon.com/asl/
      or in the "license" file accompanying this file. This file is distributed on an "AS IS"
      BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
      License for the specific language governing permissions and limitations under the License.'

  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Route 53 Parameters
        Parameters:
          - WPDomainName
          - DnsEndpoint
          - DnsHostId
          - HostedZoneId
    ParameterLabels:
      DnsEndpoint:
        default: DNS Endpoint
      DnsHostId:
        default: DNS Host Id
      WPDomainName:
        default: Site Domain
      HostedZoneId:
        default: Existing Hosted Zone Id

Parameters:
  DnsEndpoint:
    AllowedPattern: ^(?!http)(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$
    Description: The DNS endpoint - CloudFront DNS if using CloudFront else Public ELB DNS name.
    Type: String
  DnsHostId:
    AllowedPattern: ^[A-Z0-9]{5,20}$
    Description: The DNS host zone id - 'Z2FDTNDATAQYW2' if using CloudFront else Public ELB host zone id.
    Type: String
  WPDomainName:
    AllowedPattern: ^(?!http)(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$
    Description: The main domain name of the WordPress site (e.g. example.com).
    Type: String
  HostedZoneId:
    Description: '[Optional] Route53 Hosted Zone ID'
    Type: AWS::Route53::HostedZone::Id

Resources:
  CreateRecord:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZoneId
      RecordSets:
        - Name: !Join ['', ['www.', !Ref WPDomainName, '.']]
          Type: A
          AliasTarget:
            DNSName: !Ref DnsEndpoint
            EvaluateTargetHealth: True
            HostedZoneId: !Ref DnsHostId
        - Name: !Join ['', [!Ref WPDomainName, '.']]
          Type: A
          AliasTarget:
            DNSName: !Ref DnsEndpoint
            EvaluateTargetHealth: True
            HostedZoneId: !Ref DnsHostId
